/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#434655",
        "on-primary": "#ffffff",
        "surface-tint": "#0053db",
        "primary-container": "#2563eb",
        "on-primary-fixed": "#00174b",
        "on-tertiary-fixed-variant": "#653e00",
        "surface-container-high": "#dce9ff",
        "surface-bright": "#f8f9ff",
        "surface-container-highest": "#d3e4fe",
        "on-secondary": "#ffffff",
        "tertiary-container": "#996100",
        "secondary-fixed": "#6ffbbe",
        "on-secondary-container": "#00714d",
        "on-secondary-fixed": "#002113",
        "on-tertiary-container": "#ffeedd",
        "outline-variant": "#c3c6d7",
        "tertiary-fixed": "#ffddb8",
        "error-container": "#ffdad6",
        "secondary-container": "#6cf8bb",
        "on-surface": "#0b1c30",
        "tertiary": "#784b00",
        "inverse-surface": "#213145",
        "outline": "#737686",
        "primary": "#004ac6",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface": "#f8f9ff",
        "secondary": "#006c49",
        "inverse-primary": "#b4c5ff",
        "surface-container": "#e5eeff",
        "on-secondary-fixed-variant": "#005236",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#4edea3",
        "on-primary-container": "#eeefff",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#b4c5ff",
        "on-primary-fixed-variant": "#003ea8",
        "surface-variant": "#d3e4fe",
        "surface-dim": "#cbdbf5",
        "on-background": "#0b1c30",
        "background": "#f8f9ff",
        "tertiary-fixed-dim": "#ffb95f",
        "error": "#ba1a1a",
        "inverse-on-surface": "#eaf1ff",
        "on-error-container": "#93000a",
        "primary-fixed": "#dbe1ff",
        "on-tertiary-fixed": "#2a1700"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "gutter": "24px",
        "xl": "40px",
        "md": "16px",
        "lg": "24px",
        "margin-desktop": "48px",
        "unit": "4px",
        "xs": "4px",
        "sm": "8px"
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "display-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-lg": ["Inter"],
        "label-md": ["Inter"],
        "label-sm": ["Inter"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "display-lg": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-lg": ["28px", {"lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "20px", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
